blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.articles_list, name='articles_list'),
    path('detail/<slug:slug>/', views.article_detail, name='article_detail'),
    path('search/', views.search, name='search_articles'),
    path('category_create/', views.category_create, name='category_create'),
    path('article_create/', views.article_create, name='article_create'),
    path('article_update/<slug:slug>/', views.article_update, name='article_update'),
    path('article_confirm_delete/<slug:slug>/', views.article_delete, name='article_delete'),
]

blogify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=70)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, related_name='articles')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    image_banner = models.ImageField(upload_to='images/article/banner', blank=True, null=True)
    image_detail = models.ImageField(upload_to='images/article/detail', blank=True, null=True)
    active = models.BooleanField(default=True)
    views = models.IntegerField(default=0, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[self.slug])

blog/forms.py
from django import forms
from .models import Category, Article


class CreateCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title']


class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['author', 'category', 'title', 'slug', 'body', 'image_banner', 'image_detail', 'active']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article
from .forms import CreateCategory, CreateArticle
from django.core.paginator import Paginator
# Create your views here.


# def custom_404_view(request, exception):
#     return render(request, '404.html', status=404)


def articles_list(request):
    articles = Article.objects.filter(active=True)
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 4)
    object_list = paginator.get_page(page_number)
    return render(request, 'blog/articles_list.html', {'articles': object_list})


def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    article.views += 1
    article.save()
    return render(request, 'blog/article_detail.html', {'article': article})


def search(request):
    search_article = request.GET.get('search')
    articles = Article.objects.filter(title__icontains=search_article)
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 4)
    object_list = paginator.get_page(page_number)
    return render(request, 'blog/articles_list.html', {'articles': object_list})


def category_create(request):
    if request.method == 'POST':
        forms = CreateCategory(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('blog:articles_list')
    else:
        forms = CreateCategory()
    return render(request, 'blog/category_create.html', {'forms': forms})


def article_create(request):
    if request.method == 'POST':
        forms = CreateArticle(request.POST, request.FILES)
        if forms.is_valid():
            forms.save()
            return redirect('blog:articles_list')
    else:
        forms = CreateArticle()
    return render(request, 'blog/article_create.html', {'forms': forms})


def article_update(request, slug):
    articles = get_object_or_404(Article, slug=slug)
    forms = CreateArticle(request.POST or None, request.FILES or None, instance=articles)
    if forms.is_valid():
        forms.save()
        return redirect('blog:articles_list')
    return render(request, 'blog/article_update.html', {'articles': articles, 'forms': forms})


def article_delete(request, slug):
    article = get_object_or_404(Article, slug=slug)
    if request.method == 'POST':
        article.delete()
        return redirect('blog:articles_list')
    return render(request, 'blog/article_confirm_delete.html', {'article': article})

blog/templates/blog/article_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Article Confirm Delete{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 121px;margin-bottom: 390px">
    <h2 style="color: green;margin-bottom: 30px">Article Confirm Delete</h2>
    <p>Are you sure you want to delete "{{ article.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm</button>
        <a href="{% url 'blog:articles_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
    </div>
{% endblock %}

blog/templates/blog/article_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Article Create{% endblock %}

{% block content %}
    <div class="container mt-4">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2 style="color: green;margin-bottom: 30px">Article Create</h2>
            {{ forms|crispy }}
            <button type="submit" class="btn btn-primary mt-2">Article Create</button>
            <a href="{% url 'blog:category_create' %}" type="button" class="btn btn-secondary mt-2">Category Create</a>
            <a href="{% url 'blog:articles_list' %}" class="btn btn-danger mt-2">Cancel</a>
            <br>
            <br>
        </form>
    </div>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% block title %}{{ article.title }}{% endblock %}
{% load static %}

{% block content %}
    <article class="blog-post px-3 py-5 p-md-5">
        <div class="container single-col-max-width">
            <header class="blog-post-header">
                <h2 class="title mb-2">{{ article.title }}</h2>
                <div class="meta mb-1">
                    <span class="date">{{ article.created }}</span>
                    {% for category in article.category.all %}
                        <span class="comment">{{ category.title }}</span>
                    {% endfor %}
                    <span>{{ article.author }}</span>
                </div>
            </header>

            <div class="blog-post-body">
                <figure class="blog-banner">
                    {% if article.image_detail %}
                        <img class="img-fluid" src="{{ article.image_detail.url }}" alt="{{ article.title }}" width="100%">
                    {% else %}
                        <img class="img-fluid" src="{% static 'images/image_not_available.jpg' %}"
                             alt="{{ article.title }}" width="100%">
                    {% endif %}
                </figure>
                <p style="text-align: justify;line-height: 2">{{ article.body }}</p>

                <div class="d-grid gap-2 d-md-block">
                    <a href="{% url 'blog:article_update' article.slug %}" class="btn btn-info" type="button">Update</a>
                    <a href="{% url 'blog:article_delete' article.slug %}" class="btn btn-danger"
                       type="button">Delete</a>
                </div>
            </div><!--//container-->
        </div>
    </article>
{% endblock %}

blog/templates/blog/article_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Article Update{% endblock %}

{% block content %}
    <div class="container mt-4">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2 style="color: green;margin-bottom: 30px">Article Update</h2>
            {{ forms|crispy }}
            <button type="submit" class="btn btn-primary mt-2">Article Update</button>
            <a href="{% url 'blog:articles_list' %}" class="btn btn-danger mt-2">Cancel</a>
            <br>
            <br>
        </form>
    </div>
{% endblock %}

blog/templates/blog/articles_list.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% load static %}

{% block content %}
    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center single-col-max-width">
			    <h2 class="heading">Blogify - A Place To Increase Knowledge</h2>
			    <div class="intro">Welcome to my blog. Read the articles well to improve your knowledge about programming languages.</div>
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center" role="search" name="gs" method="GET" action="{% url 'blog:search_articles' %}">
	                    <div class="col-12 col-md-9">
	                        <label class="sr-only" for="search">Search Article</label>
	                        <input type="search" id="search" name="search" class="form-control me-md-1 search" placeholder="Search Article">
	                    </div>
	                    <div class="col-12 col-md-2">
	                        <button type="submit" class="btn btn-primary">Search</button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
		    </div><!--//container-->
	    </section>

    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">
			    {% for article in articles %}
                    <div class="item mb-5">
				    <div class="row g-3 g-xl-0">
					    <div class="col-2 col-xl-3">
                            {% if article.image_banner %}
                                <a href="{{ article.get_absolute_url }}"><img class="img-fluid post-thumb " src="{{ article.image_banner.url }}" alt="{{ article.title }}"></a>
                            {% else %}
                                <a href="{{ article.get_absolute_url }}"><img class="img-fluid post-thumb " src="{% static 'images/image_not_available.jpg' %}" alt="{{ article.title }}"></a>
                            {% endif %}
					    </div>
					    <div class="col">
						    <h3 class="title mb-1"><a class="text-link" href="{{ article.get_absolute_url }}" style="text-decoration: none;">{{ article.title }}</a></h3>
						    <div class="meta mb-1">
                                <span class="date">{{ article.created }}</span>
                                {% for category in article.category.all %}
                                    <span class="comment">{{ category.title }}</span>
                                {% endfor %}
                                <span>{{ article.author }}</span>
                            </div>
						    <div class="intro">{{ article.body|truncatewords:20 }}</div>
						    <a class="text-link" href="{{ article.get_absolute_url }}" style="text-decoration: none;">Read more &rarr;</a>
					    </div><!--//col-->
				    </div><!--//row-->
			    </div><!--//item-->
                {% endfor %}
		    </div>
			<!-- Pagination-->
			<nav aria-label="Pagination">
				{% if articles.has_other_pages %}
					<ul class="pagination justify-content-center my-4">
						{% if articles.has_previous %}
							<li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" tabindex="-1" aria-disabled="true">&laquo;</a></li>
						{% endif %}
						{% for page in articles.paginator.page_range %}
							{% if articles.number == page %}
								<li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ page }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ page }}</a></li>
							{% else %}
								<li class="page-item" aria-current="page"><a class="page-link" href="?page={{ page }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ page }}</a></li>
							{% endif %}
						{% endfor %}
						{% if articles.has_next %}
							<li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">&raquo;</a></li>
						{% endif %}
					</ul>
				{% endif %}
			</nav>
	    </section>
{% endblock %}

blog/templates/blog/category_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Category Create{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 100px;margin-bottom: 373.5px">
        <form method="post">
            {% csrf_token %}
            <h2 style="color: green;margin-bottom: 30px">Category Create</h2>
            {{ forms|crispy }}
            <button type="submit" class="btn btn-primary mt-2">Category Create</button>
            <a href="{% url 'blog:article_create' %}" type="button" class="btn btn-secondary mt-2">Article Create</a>
            <a href="{% url 'blog:articles_list' %}" class="btn btn-danger mt-2">Cancel</a>
            <br>
            <br>
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}">

    <!-- FontAwesome JS-->
    <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'css/theme-1.css' %}">

    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        body {
            display: flex;
            flex-direction: column;
        }

        .main-wrapper {
            flex: 1;
        }

        footer {
            flex-shrink: 0;
            background-color: #343a40;
            color: white;
            text-align: center;
            padding: 20px 0;
        }
    </style>
</head>

<body>
    <header class="header text-center">
      <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="{% url 'blog:articles_list' %}">Blogify</a></h1>

      <nav class="navbar navbar-expand-lg navbar-dark" >
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div id="navigation" class="collapse navbar-collapse flex-column" >
        <div class="profile-section pt-3 pt-lg-0">
            <img class="profile-image mb-3 rounded-circle mx-auto" src="{% static 'images/me.jpg' %}" alt="image" style="width: 150px" >

          <div class="bio mb-3">
                        <p style="text-align: justify;line-height: 1.5;">Hi, I'm Arvin Maroufi. I am a web developer working in the backend sector. I am fully specialized in Python programming language and Django framework. I love to learn new things and share my knowledge with others and help others.</p>
                        <p>Find out more about me</p>
                    </div><!--//bio-->
          <ul class="social-list list-inline py-3 mx-auto">
                  <li class="list-inline-item"><a href="https://t.me/arvinmaroufi_ir" target="_blank"><i class="fab fa-telegram fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="https://instagram.com/arvinmaroufi.ir" target="_blank"><i class="fab fa-instagram fa-fw"></i></a></li>
                  <li class="list-inline-item"><a href="https://github.com/arvinmaroufi" target="_blank"><i class="fab fa-github-alt fa-fw"></i></a></li>
              </ul><!--//social-list-->
              <hr>
        </div><!--//profile-section-->

        <ul class="navbar-nav flex-column text-start">
          <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'articles_list' %}active{% endif %}" href="{% url 'blog:articles_list' %}"><i class="fas fa-home fa-fw me-2"></i>Blog Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>

        <div class="my-2 my-md-3">
            <a class="btn btn-primary" href="{% url 'blog:article_create' %}">Create Article</a>
        </div>
      </div>
    </nav>
    </header>

    <div class="main-wrapper">
      {% block content %}{% endblock %}
    </div><!--//main-wrapper-->

    <footer class="footer text-center py-2 theme-bg-dark">
        <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <b>Arvin Maroufi</b></small>
    </footer>

    <!-- Javascript -->
    <script src="{% static 'plugins/popper.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>